name: biyi_app
description: A convenient translation and dictionary app written in Flutter.
homepage: https://github.com/lijy91/biyi
publish_to: "none"
version: 0.5.0+21

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  biyi_advanced_features:
    path: ../../packages/biyi_advanced_features
  biyi_api_client:
    path: ../../packages/biyi_api_client
  bot_toast: ^4.1.3
  collection: ^1.18.0
  easy_localization: ^3.0.3
  fluentui_system_icons: ^1.1.255
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+2
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  go_router: ^13.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hotkey_manager: ^0.2.2
  json_annotation: ^4.8.0
  keypress_simulator: ^0.2.0
  launch_at_startup: ^0.3.1
  ocr_engine_builtin: ^0.1.1
  ocr_engine_youdao: ^0.1.1
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  protocol_handler: ^0.1.6
  provider: ^6.1.1
  reflect_colors: ^0.0.1
  reflect_ui: 0.0.0
  reorderables: ^0.6.0
  screen_capturer: ^0.2.2
  screen_retriever: ^0.2.0
  screen_text_extractor: ^0.1.3
  shortid: ^0.1.2
  sticky_headers: ^0.3.0+2
  translation_engine_baidu: ^0.1.6
  translation_engine_caiyun: ^0.1.6
  translation_engine_deepl: ^0.1.6
  translation_engine_google: ^0.1.6
  translation_engine_iciba: ^0.1.6
  translation_engine_openai: ^0.1.6
  translation_engine_tencent: ^0.1.6
  translation_engine_youdao: ^0.1.6
  tray_manager: ^0.2.1
  uni_ocr_client: ^0.1.1
  uni_platform: ^0.1.0
  uni_translate_client: ^0.1.7
  url_launcher: ^6.2.2
  vclibs: ^0.1.0
  window_manager: ^0.3.9

dev_dependencies:
  build_runner: ^2.4.4
  dependency_validator: ^3.2.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mostly_reasonable_lints: ^0.1.2

dependency_overrides:
  reflect_ui:
    git:
      path: packages/reflect_ui
      url: https://github.com/leanflutter/reflect_ui.git
    # path: ../../../../leanflutter/reflect_ui/packages/reflect_ui
  screen_retriever: 0.2.0

flutter:
  uses-material-design: false
  assets:
    - resources/images/
    - resources/images/flag_icons/
    - resources/images/ocr_engine_icons/
    - resources/images/translation_engine_icons/

  fonts:
    - family: Inter
      fonts:
        - asset: resources/fonts/Inter-Thin.ttf
          weight: 100
        - asset: resources/fonts/Inter-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: resources/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: resources/fonts/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: resources/fonts/Inter-Light.ttf
          weight: 300
        - asset: resources/fonts/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: resources/fonts/Inter-Regular.ttf
          weight: 400
        - asset: resources/fonts/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: resources/fonts/Inter-Medium.ttf
          weight: 500
        - asset: resources/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: resources/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: resources/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: resources/fonts/Inter-Bold.ttf
          weight: 700
        - asset: resources/fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: resources/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: resources/fonts/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: resources/fonts/Inter-Black.ttf
          weight: 900
        - asset: resources/fonts/Inter-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Roboto Mono
      fonts:
        - asset: resources/fonts/RobotoMono-Regular.ttf
